# -*- coding: utf-8 -*-
"""CalculadoraJonathas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14CaTS6EXpZZV_VH7yMPak6MLWtijEIpR
"""

# Irei criar uma calculadora com todas as operações matemáticas possíveis
# Criação de um "menu" simples para dar inicialização na calculadora
nome_usuario = input("Digite seu nome de usuário para iniciar: ")
print(f"Olá, {nome_usuario}! Bem-vindo à Calculex 33.000!\nAqui abaixo, será solicitado dois números e qual operação deseja realizar com eles.\nOBS: Tenha em mente que o cálculo irá ocorrer da seguinte maneira:\nNúmero 1 (Operação escolhida) número 2")
print("Segue exemplo: 8.5 x 9.3 = 79.05")
print("As operações possíveis são:\nSoma, Subtração, Multiplicação, Divisão, Módulo/Resto da divisão, Potenciação e Raiz quadrada (Será calculada a raiz quadrada de ambos os números).")


while True:

# input() sempre retorna string, então tentamos converter para float;
# se o usuário digitar algo que não seja número (ex: "abc"), ValueError é
# disparado e pedimos de novo, até a conversão dar certo.
  while True:
      numero_1 = input("Digite o primeiro número: ")
      try:
          numero_1 = float(numero_1)
          break
      except ValueError:
          print("Apenas números são aceitos. Por favor, tente novamente.")

  # Mesma validação do número anterior, agora para o segundo número.
  while True:
      numero_2 = input("Digite o segundo número: ")
      try:
          numero_2 = float(numero_2)
          break
      except ValueError:
          print("Apenas números são aceitos. Por favor, tente novamente.")

  # Dicionário chave->nome: usado tanto para validar se a opção digitada
  # existe quanto para exibir o nome da operação escolhida ao usuário.
  operacoes_disponiveis = {'1':'Soma','2':'Subtração','3':'Multiplicação','4':'Divisão','5':'Módulo/Resto da Divisão','6':'Potenciação','7':'Raiz Quadrada'}
  operacao_escolhida = input("Por favor, selecione o número da operação desejada:\n1 - Soma\n2 - Subtração\n3 - Multiplicação\n4 - Divisão\n5 - Módulo/Resto da Divisão\n6 - Potenciação\n7 - Raiz Quadrada(Nesse caso, será calculada a raiz quadrada de ambos os números)\n")

  # Repete a pergunta até o usuário digitar uma chave que exista no dicionário.
  while True:
      if operacao_escolhida not in operacoes_disponiveis:
          operacao_escolhida = input("Operação inválida. Por favor, selecione um número 1 - 7\n")
      else:
          print(f"Você selecionou a operação {operacoes_disponiveis[operacao_escolhida]}.")
          break

  # Executa o cálculo correspondente à operação escolhida e exibe o resultado.
  if operacao_escolhida == '1':
      print(f"{numero_1} + {numero_2} = {numero_1 + numero_2}")

  elif operacao_escolhida == '2':
      print(f"{numero_1} - {numero_2} = {numero_1 - numero_2}")

  elif operacao_escolhida == '3':
      print(f"{numero_1} x {numero_2} = {numero_1 * numero_2}")

  elif operacao_escolhida == '4':
      print(f"{numero_1} / {numero_2} = {numero_1 / numero_2}")

  elif operacao_escolhida == '5':
      print(f"{numero_1} % {numero_2} = {numero_1 % numero_2}")

  elif operacao_escolhida == '6':
      print(f"{numero_1} elevado à {numero_2} = {numero_1 ** numero_2}")

  elif operacao_escolhida == '7':
      raiz_numero1 = numero_1 ** 0.5
      raiz_numero2 = numero_2 ** 0.5
      print(f"Raiz quadrada de {numero_1} = {raiz_numero1}")
      print(f"Raiz quadrada de {numero_2} = {raiz_numero2}")

# Pergunta se o usuário quer fazer outro cálculo ou sair do programa.
# '.strip()' remove espaços em branco (e quebras de linha) do início e do fim de uma string ("  s     " -> "s").
# '.lower()' converte a resposta do usuario para minusculo (S, s -> s).
  while True:
    continuar = input("\nDeseja realizar outro cálculo? (s/n): ").lower().strip()
    if continuar in ('s', 'n'):
        break
    print("Resposta inválida. Digite 's' para sim ou 'n' para não.")

  if continuar == 'n':
    print(f"\nAté mais, {nome_usuario}! Obrigado por usar a Calculex 33.000.")
    break